repos:  
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.10
        args: [--line-length=79]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files", --line-length=79]
        files: \.py$

  - repo: https://github.com/pycqa/pylint
    rev: v2.13.5
    hooks:
      - id: pylint
        language: system
        types: [python]
